server:
  port: 8001
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/users
  jpa:
    hibernate:
      ddl-auto: create-drop
defaultDepartmentId: 1